language: scala
sudo: false
jdk: oraclejdk8
script:
  - sbt ";set g8Properties in g8 in Test ~= { _ ++ Map((\"scala_version\" -> \"$TRAVIS_SCALA_VERSION\"), (\"sbt_version\" -> \"$SBT_VERSION\")) }; g8Test"
matrix:
  include:
  - scala: 2.11.12
    env: SBT_VERSION="0.13.18"
  - scala: 2.11.12
    env: SBT_VERSION="1.2.8"
  - scala: 2.12.8
    env: SBT_VERSION="0.13.18"
  - scala: 2.12.8
    env: SBT_VERSION="1.2.8"
